import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./src/Header/Header";
import Footer from "./src/Footer/Footer";
import Home from "./page";
import Card from "./src/Cards/Card";
import Hero from "./src/Hero/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Header/>
      <Hero/>
      <Card/>
      

      <Footer/>
     
    </html>
  );
}
